### ISSUE TITLE
Problems when installing on Windows

### ISSUE THREAD

**Issue by sebie** [IonicaBizau/github-contributions#31]
Hi,

I am having problems installing it in Windows. I read through the installation guide and tried to download and install it through PowerShell and Cygwin. In both I get errors. 

In: * PowerShell it does not recognise the `wget` or `curl` . Also the `-qO-` in the wget command throws an error.
     * In Cygwin, the installer works, but I think there is something wrong with Node?

Thanks,

Sebie

(Also, can you tag it with "Question" ? I think that is the appropriate label..)

**Comment by sebie** [comment]
Ok, so progress on it is.

I installed it by just downloading the ZIP file via GitHub, the exec didn't work.

Anyhow I got the localhost server running, via npm.

But when try to download a repository, that has been generated it says: "Not found".

**Comment by IonicaBizau** [comment]
Yes, because this is not supported on Windows yet...

**Comment by sebie** [comment]
Well I guess then you could say everything is working as planned. Only that I had to download it as a ZIP.

**Comment by IonicaBizau** [comment]
I'm on it. Testing on Windows will be needed. :smile:

**Comment by apertureless** [comment]
You can try the [Babun Shell](https://babun.github.io/) for windows. It should pretty much work out of the box. I guess you have to install node.js / npm. 

After generating, I also got the bug that the file was not found, but it's because the script didn't pack it into a zip. But the folder is there, so you can just cd into it and git push it.

**Comment by IonicaBizau** [comment]
@apertureless Checkout the `1.0.0` branch. The next version will have Windows support, using OS agnostic code. Anyway, glad to hear it worked on Windows with Babun shell. :smile:

**Comment by sebie** [comment]
Sorry for the late reply. 

Worked!

**Comment by IonicaBizau** [comment]
@sebie Cool! Preparing to release 1.0.0.

**Comment by ComFreek** [comment]
@IonicaBizau Thanks for the update! I like the new design :smile:

**Comment by IonicaBizau** [comment]
@ComFreek Glad you like it! It's [CaiuSS](https://github.com/IonicaBizau/CaiuSS).

**Comment by ComFreek** [comment]
@IonicaBizau Even a CSS framework, is there something you are currently **not** working on? :smiley:

**Comment by IonicaBizau** [comment]
Hahaha! Probably these days I should prepare for the last two exams this semester. :smile:
