### ISSUE TITLE
Maybe it don't work

### ISSUE THREAD

**Issue by hacpai** [IonicaBizau/github-contributions#33]

**Comment by IonicaBizau** [comment]
@arcticlion See [this](https://twitter.com/IonicaBizau/status/550664652808798209). Contributions graph went fishy also. :smile:

**Comment by arcticlion** [comment]
Oh, I see. It’s Github bug. No wonder, I submit the code today, it don’t show. 
-- 
Finch
Sent with Airmail

在 2015年1月1日 下午10:59:54, Ionică Bizău (notifications@github.com) 写到:

@arcticlion See this. Contributions graph went fishy also.
