### ISSUE TITLE
Instructions to update or delete the commits

### ISSUE THREAD

**Issue by codeandrop** [IonicaBizau/github-contributions#38]
Hi @IonicaBizau, nice project!
I was wondering if you have instructions when I want to update or delete the contributions calendar. I can help updating the wiki or the README file.
Let me know.
Thanks!

**Comment by IonicaBizau** [comment]
Hey!

Thanks! I'm glad you like this project.

> I was wondering if you have instructions when I want to update or delete the contributions calendar.

Theoretically, you should be able to delete the commits like in any git repository and make a force `push` on the remote. While, it is expected that the graph to be updated, I guess it will not be updated.

In practice, for deleting the contributions, simply delete the repository. To add new things on the contributions, simply create new repositories which will create graphs to overlap the others. :smile: 

As always, I am happy to accept contributions! :sparkles:

**Comment by codeandrop** [comment]
Thank you for your response! I will update the README and send you a pull request when I'm done.
