### ISSUE TITLE
Special characters?

### ISSUE THREAD

**Issue by lefoy** [IonicaBizau/github-contributions#41]
First I would like to thank you for this tool, I have a lot of fun with it :)

I'd like to know if it's possible to use the `Generate data from text` button with special characters?

I understand this could be hard to implement, but I'd like to know if there's a workaround, especially for the heart character. For example, I'd like to write "I ♥ GITHUB". 

Thanks for your help!

**Comment by IonicaBizau** [comment]
For this message there is already [a template](https://github.com/IonicaBizau/github-contributions/blob/master/samples/I-love-Github.json).

In general, follow the following steps:

 1. Write the text in the text input (e.g. `                  I        GitHub`). 
 2. Press the <kbd>:arrow_up: Generate data from text</kbd> button.
 3. Press the <kbd>:eyes: Toggle calendar days from data</kbd> button. You should get the following result:

  ![image](https://cloud.githubusercontent.com/assets/2864371/7459444/b506c484-f2a4-11e4-9c4e-f5359e0932d6.png)

 4. Draw the custom things (e.g. :heart:).

   ![image](https://cloud.githubusercontent.com/assets/2864371/7459488/0a2ef864-f2a5-11e4-8e38-6cc1a3c84738.png)

 5. Press <kbd>:arrow_down: Generate data from calendar</kbd>
 6. Press <kbd>:book: Generate repository from data</kbd> to generate the repo.

**Comment by lefoy** [comment]
Oh I didn't see the template, that's what I was looking for!
Thanks for the steps, I appreciate your help :)

**Comment by IonicaBizau** [comment]
You're welcome! :smile:
