### ISSUE TITLE
Suggestion: Single commit everyday

### ISSUE THREAD

**Issue by lefoy** [IonicaBizau/github-contributions#42]
I'm not sure if this suggestion is realistic but would it be possible to create a single commit every day so our graph looks "full"?

For example, here's how my graph looks with this tool:

![Example 1](http://i.imgur.com/fSczEUJ.png)

Here's how it could look with my suggestion:

![Example 1](http://i.imgur.com/SD7X1jV.png)

Thanks again :)

**Comment by IonicaBizau** [comment]
The workaround is to create two repos: 

 - one for background (e.g. https://github.com/IonicaBizau/calendar-background)
 - one for text (e.g. https://github.com/IonicaBizau/I-Love-Octocats/)

However, there is feature request to add pressure - that would be awesome! /cc #37.

**Comment by lefoy** [comment]
Smart. I'll create two repos :)
The pressure feature would be very nice too!
