### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by robertmain** [IonicaBizau/github-contributions#45]
GitHub already has this. Why does this exist?

**Comment by IonicaBizau** [comment]
This project *generates* activity (more specifically commits), which being pushed on GitHub shows a nice contributions chart, how you drew it via GitHub Contributions tool.

> Why does this exist?

Just for fun. I used it to write nice messages on my contributions graph (e.g. *I :heart: GitHub* or *I :heart: octocats :octocat:*). For reference, see [this article](http://ionicabizau.net/blog/9-switzerland-github-and-octocats).

Hope I made it clear. If you have any other questions, just ask me. :smile:
