### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by Tolsadus** [IonicaBizau/github-contributions#51]
Hi,

I was wondering, does it take time to see the "art" on our github ?
Or maybe i've done something wrong... :(

Max.

**Comment by IonicaBizau** [comment]
Hey @Tolsadus!

You have to set your git email same you have on GitHub settings.
https://help.github.com/articles/setting-your-email-in-git/

Then generate and create your repository again.

Cheers! :sparkle:

**Comment by Tolsadus** [comment]
Hey @IonicaBizau !

Thanks a lot :cat: . You rock !

Cheers! :santa:

**Comment by IonicaBizau** [comment]
@Tolsadus You're welcome! Seems you had fun with this tool. :joy:
