### ISSUE TITLE
Too large cost

### ISSUE THREAD

**Issue by aleen42** [IonicaBizau/github-contributions#56]
- when setting the value of "commitsPerDay" to **over 200**, it'll has been over 5 hours to generate, but without any responses.

**Comment by IonicaBizau** [comment]
Of course, because that means it generates `200 x <how many green squares>` which obviously takes a long time, depending on the HDD. All these commits are created one by one, not in the same time.

I have an SSD on my machine so it's probably faster than an HDD. :grin:

**Comment by aleen42** [comment]
Come on, the process of zipping has been a disaster, and I think you should choose another way to show the directory you have just created, rather than completing the download function.

Probably, you can use ActiveXObject to open the file directly:

```js
"use strict";
try {
    let obj = new ActiveXObject('wscript.shell');   
    if (obj) {
        obj.Run('"' + fileName + '"', 1, false);
        obj = null;
    }
} catch(e) {
    alert("the repo is failed to generate.");   
}   
```

**Comment by IonicaBizau** [comment]
> Come on, the process of zipping has been a disaster

I totally agree. In the meantime you can `cd` in `gh-contributions/lib/public/repos` (in the installation directory) and there you will find the git directories.

Contributions are always welcome. I currently have no time to improve this, but I'm happy to merge good PRs. :smile:

**Comment by aleen42** [comment]
The history cannot show soon in Github after I have added around 1000 commits.

**Comment by IonicaBizau** [comment]
@aleen42 It taks a bit to crunch all the data, but in case it fails I know a trick: create a branch, and select it as default branch, then select `master` as default branch again.

**Comment by aleen42** [comment]
@IonicaBizau I'll try it. Thx!!

**Comment by aleen42** [comment]
awesome, the trick works well. Maybe a few days I'll give you a contribution.

**Comment by aleen42** [comment]
- Problem:

```
> ./lib/server.js

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "e:\\Program Files\\nodejs\\node.exe" "e:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! gh-contributions@2.2.1 start: `./lib/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gh-contributions@2.2.1 start script './lib/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gh-contributions package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./lib/server.js
```

- Solution: I found that I should add node before to run js files, or with error when only using '.'

**Comment by aleen42** [comment]
@IonicaBizau I'll give a contribution for this and the issue of compression

**Comment by IonicaBizau** [comment]
@aleen42 Good catch! Because of Windows we should use `node lib/server.js` instead of `./lib/server.js`. :+1:

**Comment by IonicaBizau** [comment]
Thanks for fixing this in #57. :cake:
