### ISSUE TITLE
"Uncaught ReferenceError: $day is not defined" when cursor moves over a cell

### ISSUE THREAD

**Issue by shinmai** [IonicaBizau/github-contributions#64]
Get this in both the latest Chrome and Edge versions. Everything else aside from the "smooth" painting and erasing modes seem to work despite the errors.

```
index.js:266 Uncaught ReferenceError: $day is not defined
    at SVGRectElement.<anonymous> (index.js:266)
    at SVGRectElement.handle (jquery.min.js:1382)
    at HTMLDocument.dispatch (jquery.min.js:1316)
    at HTMLDocument.v.handle (jquery.min.js:1253)
(anonymous) @ index.js:266
handle @ jquery.min.js:1382
dispatch @ jquery.min.js:1316
v.handle @ jquery.min.js:1253
```

**Comment by IonicaBizau** [comment]
Can you send a screenshot of the file where the error appears?

If you installed via `npm`, you may have the transpiled version, therefore different line numbers.

Thanks!

**Comment by IonicaBizau** [comment]
Closing due to no reply...
